services:
  db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    restart: unless-stopped
    container_name: my-postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pwd
      POSTGRES_DB: my_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #  - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
       -  "11434:11434"
    volumes:
      - C:/Users/fabia/.ollama:/root/.ollama
  app:
    build: .
    container_name: app
    env_file:
      - .env
    environment:
        HF_HUB_DOWNLOAD_TIMEOUT: 60
        OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8010:8010"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - hf_cache:/root/.cache/huggingface

    restart: unless-stopped

volumes:
  postgres_data:
  hf_cache: