services:
  db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    restart: unless-stopped
    container_name: my-postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pwd
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  app:
    build: .
    container_name: app
    ports:
      - "8010:8010"
    depends_on:
      db:
        condition: service_healthy
    
    restart: unless-stopped

volumes:
  postgres_data: