FROM python:3.11.9-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

RUN useradd -m appuser

COPY --chown=appuser:appuser . /app/

USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010", "--reload","--workers", "2"]