# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create .env
      run: |
        touch .env 
        echo secret_key="tajny_klucz_do_testow" >> .env
        echo algorithm="HS256" >> .env
        echo access_token_expire=10 >> .env
        echo refresh_token_expire_days=10 >> .env
        echo DATABASE_URL="postgresql" >> .env
        echo DATABASE_URL_LOCAL="postgre.local" >> .env
        echo BEARER_TOKEN="testy123testy123" >> .env
        echo TMDB_API="TESTYETESTTETE" >> .env
        echo GROQ_API_KEY="TESTETETET" >> .env
    
    - uses: actions/checkout@v4
    - name: Docker Setup Compose

      uses: docker/setup-compose-action@v2.1.0
    - name: Start Services with Docker Build
      run: docker compose up -d --build
  
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker compose exec -T app flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker compose exec -T app flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        docker compose exec -T app pytest
